# Generated by Django 2.0.6 on 2018-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180615_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Pressure',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='RH_percentage',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Temperature',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
    ]
