# Generated by Django 2.0.6 on 2018-06-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180615_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='EE',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Haldane',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='RH',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='RQ',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='VCO_2',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='VO_2',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
    ]
